{% set version = "0.2.3" %}

package:
  name: "scrublet"
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/bf/f8/52cecc93d2ac7b7ffe53662b60c34b2ad7f97eed7360e3d264080f8b1608/scrublet-{{ version }}.tar.gz
  sha256: 2185f63070290267f82a36e5b4cae8c321f10415d2d0c9f7e5e97b1126bf653a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
  run:
    - python
    - numpy
    - scipy
    - scikit-learn
    - scikit-image
    - matplotlib
    - annoy
    - numba
    - pandas
    - umap-learn

about:
  home: "https://github.com/swolock/scrublet"
  license: MIT
  summary: "Detect doublets in single-cell RNA-seq data"
