package:
  name: "woldlab-rna-seq"
  version: "1.3.0"

source:
  git_rev: "8e2d11642fac8e2bb4868a8a140e4b38e6ea0c36"
  git_url: "https://github.com/detrout/woldlab-rna-seq.git"

build:
  number: 5
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - git
    - python
    - pip
    - wheel
    - setuptools
    - setuptools-scm
  run:
    - python
    - jinja2 >=2.8
    - lxml
    - matplotlib >=3.0
    - {{ pin_compatible('numpy') }}
    - pandas
    - requests
    - scipy
# Not in conda-forge
# Use -c bioconda -c https://woldlab.caltech.edu/~diane/conda to build
    - encoded_client >=0.3.0
    - mex_gene_archive >=0.2.1
    - pysam
    - xopen
# Too old
#    - bokeh >=0.12.10,<1.0

about:
  home: "https://github.com/detrout/woldlab-rna-seq.git"
  license: BSD
  license_file: LICENSE.txt
  summary: package for doing standardized RNA-seq analysis
