{% set version = "1.17.2" %}

package:
  name: "annoy"
  version: "{{ version }}"

source:
  git_rev: "v{{ version }}"
  git_url: "https://github.com/spotify/annoy.git"

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - setuptools
    - git
    - {{ compiler('cxx') }}
  host:
    - python
    - nose>=1.0

about:
  home: "https://github.com/spotify/annoy"
  license: Apache-2.0
  license_file: LICENSE
  summary: "Approximate Nearest Neighbors in C++/Python optimized for memory usage and loading/saving to disk"
