{% set version = "0.50.1" %}

package:
  name: "kallisto"
  version: "{{ version }}"

source:
  git_rev: "v{{ version }}"
  git_url: "https://github.com/pachterlab/kallisto.git"

build:
  number: 2
  run_exports:
    - hdf5
    - zlib >=1.2.13,<1.3.0a0   #>=1.3.1,<1.4.0a0


requirements:
  build:
    - git
    - cmake
    - {{ compiler("cxx") }}
  run:
    - requests

about:
  home: "https://www.kallistobus.tools/"
  license: BSD-2-Clause
  license_file: license.txt
  summary: Near-optimal RNA-seq quantification
